name: CI

on:
  pull_request:
  push:
    branches:
      - work
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8.15.7
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Typecheck
        run: pnpm typecheck
      - name: Unit tests
        run: pnpm test
      - name: Install Playwright browsers
        run: pnpm --filter web exec playwright install --with-deps
      - name: E2E tests
        run: pnpm test:e2e
        env:
          CI: true
      - name: Build
        run: pnpm build
